accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login', views.login_view, name="login"),
    path('register', views.register, name="register"),
    path('logout', views.logout_view, name="logout")
]

shortener/urls.py
from django.urls import path
from . import views

app_name = "shortener"

urlpatterns = [
    path('', views.shortener, name="shortener"),
    path('<slug:slug>', views.shortener, name="result"),
    path('redirect/<slug:slug>', views.redirect_view, name="redirect"),
]

urlshortener/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls')),
    path('shortener/', include('shortener.urls'))
]

accounts/models.py
from django.db import models

# Create your models here.

shortener/models.py
from django.db import models
import string
import random
# Create your models here.

class UrlShortcut(models.Model):
    raw_url = models.URLField()
    short_url = models.URLField(unique=True)
    creation_date = models.DateTimeField(auto_now_add=True)

    objects = models.Manager()

    def __str__(self):
        return self.short_url

accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model


User = get_user_model()
class RegisterForm(forms.Form):
    email = forms.EmailField(
            widget=forms.TextInput(
            attrs=
            {
                "class": "form-control"
            }
        )
    )
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control'
            }
        )
    )
    password = forms.CharField(
            widget=forms.PasswordInput(
                attrs={
                    'class': 'form-control'
                }
        )
    )
    confirmation_password = forms.CharField(
            widget=forms.PasswordInput(
                attrs={
                    'class': 'form-control'
                }
        )
    )
    #this function is overridden
    def clean(self):
        pass1 = self.cleaned_data.get('password')
        pass2 = self.cleaned_data.get('confirmation_password')
        if pass1 != pass2:
            raise forms.ValidationError("passwords don't match")
        return self.cleaned_data

    def clean_username(self):
        username = self.cleaned_data.get('username')
        user = User.objects.filter(username=username)
        if user.exists():
            raise forms.ValidationError('user exists')
        return self.cleaned_data.get('username')

class LoginForm(forms.Form):
    username = forms.CharField(
        label='',
        widget=forms.TextInput(
          attrs={
            'class': 'form-control'
            
        }  
    )    
)
    password = forms.CharField(
        label='',
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control'
            }
        )
    )

    def clean_user(self):
        username = self.cleaned_data.get('username')
        user = User.objects.filter(username=username)
        if user is None:
            raise forms.ValidationError("this user doesn't exist")
        return self.cleaned_data['username']

shortener/forms.py
from django import forms


class Shortener(forms.Form):
    url = forms.URLField(
        label='',
        widget=forms.URLInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Enter URL'
            }
        )
    )

accounts/views.py
from django.shortcuts import render, redirect, reverse
from .forms import RegisterForm, LoginForm
from django.http import HttpResponse
from django.contrib.auth import get_user_model, login, authenticate, login, logout
# Create your views here.



User = get_user_model()
def register(request):
    if request.user.is_authenticated:
        return redirect('shortener:shortener')
        
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            email = form.cleaned_data['email']
            User.objects.create_user(username, email, password)
            return redirect('accounts:login')
    form = RegisterForm()
    return render(request, 'accounts/register.html', {'form': form})


def login_view(request):
    if request.user.is_authenticated:
        return redirect('shortener:shortener')

    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password )
            login(request, user)
            return redirect('shortener:shortener')
    form = LoginForm()
    return render(request, 'accounts/index.html', {'form': form})

def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('accounts:login')

shortener/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import Shortener
from .models import UrlShortcut
import string,random
from django.contrib.auth.decorators import login_required
# Create your views here.

def url_generator(chars=string.ascii_lowercase+string.digits, size=5):
    rand_string = ""
    for _ in range(size):
        rand_string += random.choice(chars)
    new_url = 'http://myshortn.er/'+rand_string
    return new_url, rand_string

def unique_url(short_url):
    if UrlShortcut.objects.filter(short_url=short_url).exists():
        new_url = unique_url(url_generator())
        return new_url
    return short_url
    
@login_required(login_url='accounts:login')
def shortener(request, slug=None):
    if request.method == 'POST':
        form = Shortener(request.POST)
        if form.is_valid():
            raw_url = form.cleaned_data['url']
            new_url, slug = url_generator()
            short_url = unique_url(new_url)
            url = UrlShortcut(short_url=short_url, raw_url=raw_url)
            url.save() 
            return redirect('shortener:result', slug)
    elif slug is not None:
        url = UrlShortcut.objects.filter(short_url__icontains=slug).first()
        form = Shortener()
        context = {
            'form': form,
            'url': url,
            'slug': slug,
        }            
        return render(request, 'shortener/shortener.html', context)
    else:
        form = Shortener()
        return render(request, 'shortener/shortener.html', {'form':form})

def redirect_view(request, slug):
    url = get_object_or_404(UrlShortcut, short_url__icontains=slug)
    return redirect(f'{url.raw_url}')

accounts/templates/accounts/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
 <div class="col-5 mt-5 form">  
  <form method="POST">
    {% csrf_token %}
   <h1>Sign in</h1>
   {{form.as_p}}
   <button id="btn">SIGN IN</button>

  </form>
 </div>
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
        <div class="col-4 mx-auto mt-5">
            <form action="{% url 'accounts:login' %}" method="POST">
                {% csrf_token %}
                {{ form }}
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>

{% endblock %}

accounts/templates/accounts/register.html
{% extends 'base.html' %}

{% block content %}
<div class="col-4 mx-auto">
    <form method="POST">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>
{% endblock %}

shortener/templates/shortener/shortener.html
{% extends 'base.html' %}


{% block content %}
<div class="col-6 mx-auto mt-5">
    <form method="POST">
        <h1 class="mb-3">URL SHORTENER</h1>
        {% csrf_token %}
        {{form}}
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
    {% if url %}
    <a href="{% url 'shortener:redirect' slug %}" class="mt-2 " target="_blank">{{url.short_url}}</a>
    {% endif %}
    <form action="{% url 'accounts:logout'%}" method="POST">
        {% csrf_token %}
        <input type="submit" value="Log out">
    </form>
</div>

{% endblock %}

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://fonts.googleapis.com/css?family=Poppins|Josefin+Sans&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'accounts/style.css' %}">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

  </head>
  <body>

    {% block content %}
    
    {% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>